# Generated by Django 3.0.3 on 2020-02-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YoBroApp', '0002_auto_20200223_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='Group_members',
        ),
        migrations.RenameField(
            model_name='group_members',
            old_name='group_id',
            new_name='group',
        ),
    ]
